#!/usr/bin/env python3
"""Single stdlib authority for generated doc-only CI workflow."""
import argparse
from pathlib import Path
HEADER = '# GENERATED by scripts/ci-doc-only-topology.py; do not edit.\n'
ROLES = ('build-test', 'conformance', 'clean-room', 'path-guard')
HEAVY = ('test-shard', 'native-write-partition', 'native-buffer', 'native-rt-parity', 'z3-process-adapter', 'z3-emission-control', 'ignored-row-sweep', 'verify-realized-shard-union')
def render():
 body=Path('scripts/ci.yml.in').read_text()
 if body.startswith(HEADER): raise SystemExit('template must not be generated')
 for role in ROLES + HEAVY:
  if ('  '+role+':') not in body: raise SystemExit('missing typed topology member: '+role)
 return HEADER+body
def main():
 p=argparse.ArgumentParser();p.add_argument('command',choices=('render','check'));a=p.parse_args(); data=render()
 if a.command=='render': print(data,end='')
 elif Path('.github/workflows/ci.yml').read_text()!=data: raise SystemExit('generated workflow differs from authority')
if __name__=='__main__': main()
